name: Health
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.1
dependencies:
  flutter:
    sdk: flutter
    fl_chart: ^0.60.0
  firebase_core: ^2.24.0
  firebase_auth: ^4.16.0
  cupertino_icons: ^1.0.8
  cloud_firestore: ^4.17.5
  pedometer: ^4.0.1
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Optional: Add assets here
  # assets:
  #   - images/
